/**
 * 配置导出工具 — 将 crab-cli 全量配置序列化为 Markdown 文档
 *
 *
 * 导出内容: API Provider、MCP 服务、系统提示词、代理、主题、子代理等
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import { readMergedSettings } from "@/config/settings/unifiedSettings";

// ─── 类型 ──────────────────────────────────────────────────

export interface ConfigExportResult {
  content: string;
  filePath: string;
  exportedAt: string;
}

// ─── 内部函数 ──────────────────────────────────────────────

function ensureExportDir(): string {
  const dir = join(homedir(), ".crab", "exports");
  if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
  return dir;
}

function sanitizeForMarkdown(obj: unknown, indent = 0): string {
  const prefix = "  ".repeat(indent);

  if (obj === null || obj === undefined) return `${prefix}_null_`;
  if (typeof obj === "boolean") return `${prefix}${obj ? "true" : "false"}`;
  if (typeof obj === "number") return `${prefix}${obj}`;
  if (typeof obj === "string") {
    // 脱敏: 隐藏 API key 中间部分
    if (obj.length > 10 && /^(sk-|key-|api[_-]?key)/i.test(obj)) {
      return `${prefix}${obj.slice(0, 6)}****${obj.slice(-4)}`;
    }
    return `${prefix}\`${obj}\``;
  }

  if (Array.isArray(obj)) {
    if (obj.length === 0) return `${prefix}(empty)`;
    return obj.map((item) => `${prefix}- ${sanitizeForMarkdown(item, 0).trimStart()}`).join("\n");
  }

  if (typeof obj === "object") {
    const entries = Object.entries(obj as Record<string, unknown>);
    if (entries.length === 0) return `${prefix}(empty object)`;
    return entries
      .map(([key, value]) => {
        const valStr = sanitizeForMarkdown(value, indent + 1);
        return `${prefix}**${key}**: ${valStr.trimStart()}`;
      })
      .join("\n");
  }

  return `${prefix}${String(obj)}`;
}

function sectionTitle(title: string, level = 2): string {
  return `\n${"#".repeat(level)} ${title}\n`;
}

// ─── 公开 API ──────────────────────────────────────────────

/** 将全量配置导出为 Markdown 文档并保存到 ~/.crab/exports/ */
export function exportConfigToFile(fileName?: string): ConfigExportResult {
  const rawSettings = readMergedSettings();
  const settings = rawSettings as Record<string, unknown>;
  const timestamp = new Date().toISOString();

  const lines: string[] = [];

  // 文档头
  lines.push(`# Crab CLI Configuration Export`);
  lines.push(`\n> Exported at: ${timestamp}`);
  lines.push(`> Working directory: ${process.cwd()}`);
  lines.push(`> Crab CLI version: ${process.env.CRAB_VERSION || "unknown"}`);

  // 按类别导出已知配置段
  const SECTION_KEYS: Array<{ key: string; title: string; format?: "code" }> = [
    { key: "providers", title: "API Providers" },
    { key: "apiKeys", title: "API Keys (Sanitized)" },
    { key: "defaultProvider", title: "Default Provider" },
    { key: "mcpServers", title: "MCP Servers" },
    { key: "systemPrompt", title: "System Prompt", format: "code" },
    { key: "customHeaders", title: "Custom Headers" },
    { key: "proxyConfig", title: "Proxy Configuration" },
    { key: "subAgents", title: "Sub-Agents" },
    { key: "theme", title: "Theme" },
    { key: "toolDisplayMode", title: "Tool Display Mode" },
    { key: "hooks", title: "Hooks Configuration" },
    { key: "permissions", title: "Permissions" },
  ];

  const seenKeys = new Set<string>();

  for (const section of SECTION_KEYS) {
    const value = settings[section.key];
    if (value === undefined || value === null) continue;
    seenKeys.add(section.key);

    lines.push(sectionTitle(section.title));

    if (section.format === "code" && typeof value === "string") {
      lines.push(`\n\`\`\``);
      lines.push(value);
      lines.push(`\`\`\``);
    } else if (typeof value === "string") {
      lines.push(`\`${value}\``);
    } else {
      lines.push(sanitizeForMarkdown(value));
    }
  }

  // 其他未分类设置
  const otherKeys = Object.keys(settings).filter((k) => !seenKeys.has(k));
  if (otherKeys.length > 0) {
    lines.push(sectionTitle("Other Settings"));
    const other: Record<string, unknown> = {};
    for (const key of otherKeys) {
      other[key] = settings[key];
    }
    lines.push(sanitizeForMarkdown(other));
  }

  lines.push(`\n---\n_Generated by Crab CLI Config Exporter_`);

  const content = lines.join("\n");
  const exportDir = ensureExportDir();
  const filePath = join(exportDir, fileName || `config-export-${new Date().toISOString().slice(0, 10)}.md`);

  writeFileSync(filePath, content, "utf-8");

  return { content, filePath, exportedAt: timestamp };
}

/** 将配置导出为 Markdown 字符串（不写文件） */
export function exportConfigToString(): string {
  const result = exportConfigToFile();
  return result.content;
}
